/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Config.MsgDispatch;
import controller.Client;
import static controller.Client.curListMsgChat;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import storage.User;

/**
 *
 * @author holohoi
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        myInit();
//        System.out.println("width: " + jLabel4.getWidth());
//        System.out.println("height: " + jLabel4.getHeight());

    }

    public Dashboard(ObjectOutputStream _outStream) {
        // readMessage thread
        initComponents();
        myInit();
        this.setLocationRelativeTo(null);
        this.outStream = _outStream;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void myInit() {
        loadingLabel = new javax.swing.JLabel();
        loadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/loading.gif"))); // NOI18N
        loadingLabel.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        loadingLabel.setBackground(Color.WHITE);
        loadingLabel.setOpaque(true);

        listMsgContactsPanel = new ListMsgContactPanel(Client.listContacts, Client.listMsgContacts, Client.setContacts);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                scrollNavMsgContacts.setViewportView(listMsgContactsPanel);
            }
        });
//        jLabel4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background.jpg")).getImage().getScaledInstance(bodyMain.getWidth(), bodyMain.getHeight(), Image.SCALE_SMOOTH)));
        bodyMain.setVisible(false);
        bodyMessage.setVisible(true);
        setSessionPanelNav("navMain");
        setSessionPanelBody("bodyMain");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListMsgContacts = new javax.swing.JPanel();
        eachMessage4 = new javax.swing.JPanel();
        avatar1 = new javax.swing.JLabel();
        nameB1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        contentMsg1 = new javax.swing.JLabel();
        eachMessage5 = new javax.swing.JPanel();
        avatar2 = new javax.swing.JLabel();
        nameB2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        contentMsg2 = new javax.swing.JLabel();
        eachMessage6 = new javax.swing.JPanel();
        avatar3 = new javax.swing.JLabel();
        nameB3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        contentMsg3 = new javax.swing.JLabel();
        eachMessage7 = new javax.swing.JPanel();
        avatar4 = new javax.swing.JLabel();
        nameB4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        contentMsg4 = new javax.swing.JLabel();
        panelShowChat = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nav = new javax.swing.JPanel();
        navMain = new javax.swing.JPanel();
        panelSearchAndMenu1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        scrollNavMsgContacts = new javax.swing.JScrollPane();
        navMainTest = new javax.swing.JPanel();
        panelSearchAndMenu = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        navOption = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        bodyMessage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelContactName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelContactLastseen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputMessage = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        scrollSucess = new javax.swing.JScrollPane();
        viewPortSuccess = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        content_2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        content_1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        scrollTemp = new javax.swing.JScrollPane();
        bodyMain = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        panelListMsgContacts.setBackground(new java.awt.Color(204, 204, 255));

        eachMessage4.setBackground(new java.awt.Color(65, 159, 217));
        eachMessage4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eachMessage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eachMessage4MouseClicked(evt);
            }
        });

        avatar1.setForeground(new java.awt.Color(0, 0, 0));
        avatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        avatar1.setPreferredSize(new java.awt.Dimension(34, 34));

        nameB1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameB1.setForeground(new java.awt.Color(0, 0, 0));
        nameB1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameB1.setText("Mr.A");

        date1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(102, 102, 102));
        date1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date1.setText("22/22/2222");

        contentMsg1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contentMsg1.setForeground(new java.awt.Color(226, 239, 236));
        contentMsg1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentMsg1.setText("Content new Content new Content new message");

        javax.swing.GroupLayout eachMessage4Layout = new javax.swing.GroupLayout(eachMessage4);
        eachMessage4.setLayout(eachMessage4Layout);
        eachMessage4Layout.setHorizontalGroup(
            eachMessage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eachMessage4Layout.createSequentialGroup()
                .addComponent(avatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eachMessage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eachMessage4Layout.createSequentialGroup()
                        .addComponent(nameB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date1)
                        .addGap(15, 15, 15))
                    .addComponent(contentMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        eachMessage4Layout.setVerticalGroup(
            eachMessage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(eachMessage4Layout.createSequentialGroup()
                .addGroup(eachMessage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameB1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 459, Short.MAX_VALUE))
        );

        eachMessage5.setBackground(new java.awt.Color(255, 255, 255));

        avatar2.setForeground(new java.awt.Color(0, 0, 0));
        avatar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        avatar2.setPreferredSize(new java.awt.Dimension(34, 34));

        nameB2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameB2.setForeground(new java.awt.Color(0, 0, 0));
        nameB2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameB2.setText("Mr.A");

        date2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        date2.setForeground(new java.awt.Color(102, 102, 102));
        date2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date2.setText("22/22/2222");

        contentMsg2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contentMsg2.setForeground(new java.awt.Color(0, 153, 255));
        contentMsg2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentMsg2.setText("Content new message");

        javax.swing.GroupLayout eachMessage5Layout = new javax.swing.GroupLayout(eachMessage5);
        eachMessage5.setLayout(eachMessage5Layout);
        eachMessage5Layout.setHorizontalGroup(
            eachMessage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eachMessage5Layout.createSequentialGroup()
                .addComponent(avatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eachMessage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eachMessage5Layout.createSequentialGroup()
                        .addComponent(nameB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date2)
                        .addGap(15, 15, 15))
                    .addComponent(contentMsg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        eachMessage5Layout.setVerticalGroup(
            eachMessage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(eachMessage5Layout.createSequentialGroup()
                .addGroup(eachMessage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameB2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 459, Short.MAX_VALUE))
        );

        eachMessage6.setBackground(new java.awt.Color(255, 255, 255));

        avatar3.setForeground(new java.awt.Color(0, 0, 0));
        avatar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        avatar3.setPreferredSize(new java.awt.Dimension(34, 34));

        nameB3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameB3.setForeground(new java.awt.Color(0, 0, 0));
        nameB3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameB3.setText("Mr.A");

        date3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        date3.setForeground(new java.awt.Color(102, 102, 102));
        date3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date3.setText("22/22/2222");

        contentMsg3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contentMsg3.setForeground(new java.awt.Color(102, 102, 102));
        contentMsg3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentMsg3.setText("Content new message");

        javax.swing.GroupLayout eachMessage6Layout = new javax.swing.GroupLayout(eachMessage6);
        eachMessage6.setLayout(eachMessage6Layout);
        eachMessage6Layout.setHorizontalGroup(
            eachMessage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eachMessage6Layout.createSequentialGroup()
                .addComponent(avatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eachMessage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eachMessage6Layout.createSequentialGroup()
                        .addComponent(nameB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date3)
                        .addGap(15, 15, 15))
                    .addComponent(contentMsg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        eachMessage6Layout.setVerticalGroup(
            eachMessage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(eachMessage6Layout.createSequentialGroup()
                .addGroup(eachMessage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameB3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentMsg3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 459, Short.MAX_VALUE))
        );

        eachMessage7.setBackground(new java.awt.Color(255, 255, 255));

        avatar4.setForeground(new java.awt.Color(0, 0, 0));
        avatar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        avatar4.setPreferredSize(new java.awt.Dimension(34, 34));

        nameB4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameB4.setForeground(new java.awt.Color(0, 0, 0));
        nameB4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameB4.setText("Mr.A");

        date4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        date4.setForeground(new java.awt.Color(102, 102, 102));
        date4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date4.setText("22/22/2222");

        contentMsg4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contentMsg4.setForeground(new java.awt.Color(102, 102, 102));
        contentMsg4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentMsg4.setText("Content new message");

        javax.swing.GroupLayout eachMessage7Layout = new javax.swing.GroupLayout(eachMessage7);
        eachMessage7.setLayout(eachMessage7Layout);
        eachMessage7Layout.setHorizontalGroup(
            eachMessage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eachMessage7Layout.createSequentialGroup()
                .addComponent(avatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eachMessage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eachMessage7Layout.createSequentialGroup()
                        .addComponent(nameB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date4)
                        .addGap(15, 15, 15))
                    .addComponent(contentMsg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        eachMessage7Layout.setVerticalGroup(
            eachMessage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(eachMessage7Layout.createSequentialGroup()
                .addGroup(eachMessage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameB4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentMsg4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 459, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelListMsgContactsLayout = new javax.swing.GroupLayout(panelListMsgContacts);
        panelListMsgContacts.setLayout(panelListMsgContactsLayout);
        panelListMsgContactsLayout.setHorizontalGroup(
            panelListMsgContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eachMessage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eachMessage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eachMessage6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eachMessage7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelListMsgContactsLayout.setVerticalGroup(
            panelListMsgContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListMsgContactsLayout.createSequentialGroup()
                .addComponent(eachMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eachMessage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eachMessage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eachMessage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelShowChat.setBackground(new java.awt.Color(116, 180, 224));

        jLabel3.setText(">");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("xxxxxxxxxxxxxxxxxxxxa asdfaw asdfa asdf");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelShowChatLayout = new javax.swing.GroupLayout(panelShowChat);
        panelShowChat.setLayout(panelShowChatLayout);
        panelShowChatLayout.setHorizontalGroup(
            panelShowChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShowChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShowChatLayout.setVerticalGroup(
            panelShowChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShowChatLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        nav.setBackground(new java.awt.Color(255, 255, 255));
        nav.setLayout(new javax.swing.OverlayLayout(nav));

        navMain.setBackground(new java.awt.Color(255, 255, 255));
        navMain.setName("navMain"); // NOI18N

        panelSearchAndMenu1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setBackground(new java.awt.Color(236, 232, 232));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Search");
        jTextField2.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSearchAndMenu1Layout = new javax.swing.GroupLayout(panelSearchAndMenu1);
        panelSearchAndMenu1.setLayout(panelSearchAndMenu1Layout);
        panelSearchAndMenu1Layout.setHorizontalGroup(
            panelSearchAndMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchAndMenu1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSearchAndMenu1Layout.setVerticalGroup(
            panelSearchAndMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jTextField2)
        );

        scrollNavMsgContacts.setBorder(null);
        scrollNavMsgContacts.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout navMainLayout = new javax.swing.GroupLayout(navMain);
        navMain.setLayout(navMainLayout);
        navMainLayout.setHorizontalGroup(
            navMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollNavMsgContacts)
                    .addGroup(navMainLayout.createSequentialGroup()
                        .addComponent(panelSearchAndMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        navMainLayout.setVerticalGroup(
            navMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearchAndMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollNavMsgContacts, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );

        nav.add(navMain);
        //navMain.setVisible(false);

        navMainTest.setBackground(new java.awt.Color(255, 255, 255));

        panelSearchAndMenu.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setBackground(new java.awt.Color(236, 232, 232));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Search");
        jTextField1.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelSearchAndMenuLayout = new javax.swing.GroupLayout(panelSearchAndMenu);
        panelSearchAndMenu.setLayout(panelSearchAndMenuLayout);
        panelSearchAndMenuLayout.setHorizontalGroup(
            panelSearchAndMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchAndMenuLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSearchAndMenuLayout.setVerticalGroup(
            panelSearchAndMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchAndMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout navMainTestLayout = new javax.swing.GroupLayout(navMainTest);
        navMainTest.setLayout(navMainTestLayout);
        navMainTestLayout.setHorizontalGroup(
            navMainTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navMainTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearchAndMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        navMainTestLayout.setVerticalGroup(
            navMainTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMainTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearchAndMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        nav.add(navMainTest);
        //navMainTest.setVisible(false);

        navOption.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout navOptionLayout = new javax.swing.GroupLayout(navOption);
        navOption.setLayout(navOptionLayout);
        navOptionLayout.setHorizontalGroup(
            navOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        navOptionLayout.setVerticalGroup(
            navOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nav.add(navOption);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        nav.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        nav.add(jPanel4);

        body.setLayout(new javax.swing.OverlayLayout(body));

        bodyMessage.setBackground(new java.awt.Color(216, 227, 244));
        bodyMessage.setName("bodyMessage"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelContactName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelContactName.setForeground(new java.awt.Color(0, 0, 0));
        labelContactName.setText("Mr. Smith");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu_1.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelContactLastseen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelContactLastseen.setForeground(new java.awt.Color(102, 102, 102));
        labelContactLastseen.setText("Last seen 5 hours ago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContactName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelContactLastseen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelContactName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContactLastseen)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/link_file.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/send.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/emoji.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        inputMessage.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputMessage.setForeground(new java.awt.Color(102, 102, 102));
        inputMessage.setText("Write a message...");
        inputMessage.setBorder(null);
        inputMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputMessageMouseClicked(evt);
            }
        });
        inputMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputMessage)
        );

        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));

        scrollSucess.setBackground(new java.awt.Color(116, 180, 224));

        viewPortSuccess.setBackground(new java.awt.Color(116, 180, 224));
        viewPortSuccess.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel9.setBackground(new java.awt.Color(116, 180, 224));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("You");
        jLabel9.setMinimumSize(new java.awt.Dimension(0, 0));

        content_2.setBackground(new java.awt.Color(255, 255, 255));
        content_2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        content_2.setForeground(new java.awt.Color(0, 0, 0));
        content_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        content_2.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("jLabel6");
        jLabel12.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
            .addComponent(content_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(116, 180, 224));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("You");
        jLabel13.setMinimumSize(new java.awt.Dimension(0, 0));

        content_1.setBackground(new java.awt.Color(255, 255, 255));
        content_1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        content_1.setForeground(new java.awt.Color(0, 0, 0));
        content_1.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("jLabel5");
        jLabel14.setMinimumSize(new java.awt.Dimension(3, 3));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
            .addComponent(content_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viewPortSuccessLayout = new javax.swing.GroupLayout(viewPortSuccess);
        viewPortSuccess.setLayout(viewPortSuccessLayout);
        viewPortSuccessLayout.setHorizontalGroup(
            viewPortSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPortSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPortSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        viewPortSuccessLayout.setVerticalGroup(
            viewPortSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPortSuccessLayout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrollSucess.setViewportView(viewPortSuccess);

        jPanel6.add(scrollSucess);
        scrollSucess.setVisible(false);

        scrollTemp.setBackground(new java.awt.Color(116, 180, 224));
        scrollTemp.setBorder(null);
        scrollTemp.setAutoscrolls(true);
        scrollTemp.setHorizontalScrollBar(null);
        scrollTemp.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.add(scrollTemp);

        javax.swing.GroupLayout bodyMessageLayout = new javax.swing.GroupLayout(bodyMessage);
        bodyMessage.setLayout(bodyMessageLayout);
        bodyMessageLayout.setHorizontalGroup(
            bodyMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        bodyMessageLayout.setVerticalGroup(
            bodyMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyMessageLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        body.add(bodyMessage);

        bodyMain.setBackground(new java.awt.Color(204, 204, 255));
        bodyMain.setName("bodyMain"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select a chat to start messaging");

        javax.swing.GroupLayout bodyMainLayout = new javax.swing.GroupLayout(bodyMain);
        bodyMain.setLayout(bodyMainLayout);
        bodyMainLayout.setHorizontalGroup(
            bodyMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyMainLayout.setVerticalGroup(
            bodyMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        body.add(bodyMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        clickSendMessage();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void inputMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMessageActionPerformed
        // TODO add your handling code here:
        clickSendMessage();
    }//GEN-LAST:event_inputMessageActionPerformed

    private void inputMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputMessageMouseClicked
        // TODO add your handling code here:
        if (inputMessage.getText().equals("Write a message...")) {
            inputMessage.setForeground(new java.awt.Color(0, 0, 0));
            inputMessage.setText("");
        }
    }//GEN-LAST:event_inputMessageMouseClicked

    private void eachMessage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eachMessage4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eachMessage4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        Object[] req = new Object[]{MsgDispatch.GET_LIST_MSG_CHAT, "hehe"};
        sendReq(req);

    }//GEN-LAST:event_jLabel2MouseClicked

    void setSessionPanelNav(String sessionName) {
        Component[] cpnts = nav.getComponents();
        for (Component c : cpnts) {
            if (c.getName() != null && c.getName().equalsIgnoreCase(sessionName)) {
                c.setVisible(true);
            } else {
                c.setVisible(false);
            }
        }
        nav.revalidate();
        nav.repaint();
    }

    void setSessionPanelBody(String sessionName) {
        Component[] cpnts = body.getComponents();
        for (Component c : cpnts) {
            if (c.getName() != null && c.getName().equalsIgnoreCase(sessionName)) {
                c.setVisible(true);
            } else {
                c.setVisible(false);
            }
        }
        body.revalidate();
        body.repaint();
    }

    public void clickContactMsg(User contact) {
        labelContactName.setText(contact.getName());
        setSessionPanelBody("bodyMessage");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    void clickSendMessage() {
        String newTextMessage = inputMessage.getText();
        if (!newTextMessage.equals("")) {
            Object[] req = new Object[]{MsgDispatch.DELIVER_MSG, Client.curContact.getId(), newTextMessage};
            sendReq(req);
            inputMessage.setText("");
        }
    }

    public void requestListMsgChat(int contactId) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                scrollTemp.setViewportView(loadingLabel);
            }
        });

        Object[] req = new Object[]{MsgDispatch.GET_LIST_MSG_CHAT, contactId};
        sendReq(req);
    }

    public void renderListMsgChat() {
//        jScrollPane2.setViewportView(listMsgChatPanel);
//        String shortText = "<html><p>" + "hi" + "</p></html>";
//        String longText = "<html><p>" + "HelloHelloHello, Long time no see, how are you Mr.C?" + "</p></html>";
//
//        content_1.setText(longText);
//        content_2.setText(longText);
//        scrollTemp.setVisible(false);

        listMsgChatPanel = new ListMsgChatPanel(curListMsgChat);
        scrollTemp.setViewportView(listMsgChatPanel);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    private Image fitimage(Image img, int w, int h) {
        BufferedImage resizedimage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedimage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedimage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bodyMain;
    private javax.swing.JPanel bodyMessage;
    private javax.swing.JLabel contentMsg1;
    private javax.swing.JLabel contentMsg2;
    private javax.swing.JLabel contentMsg3;
    private javax.swing.JLabel contentMsg4;
    private javax.swing.JLabel content_1;
    private javax.swing.JLabel content_2;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JPanel eachMessage4;
    private javax.swing.JPanel eachMessage5;
    private javax.swing.JPanel eachMessage6;
    private javax.swing.JPanel eachMessage7;
    private javax.swing.JTextField inputMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelContactLastseen;
    private javax.swing.JLabel labelContactName;
    private javax.swing.JLabel nameB1;
    private javax.swing.JLabel nameB2;
    private javax.swing.JLabel nameB3;
    private javax.swing.JLabel nameB4;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel navMain;
    private javax.swing.JPanel navMainTest;
    private javax.swing.JPanel navOption;
    private javax.swing.JPanel panelListMsgContacts;
    private javax.swing.JPanel panelSearchAndMenu;
    private javax.swing.JPanel panelSearchAndMenu1;
    private javax.swing.JPanel panelShowChat;
    private javax.swing.JScrollPane scrollNavMsgContacts;
    private javax.swing.JScrollPane scrollSucess;
    private javax.swing.JScrollPane scrollTemp;
    private javax.swing.JPanel viewPortSuccess;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JPanel listMsgContactsPanel;
    private javax.swing.JPanel listMsgChatPanel;
    ObjectOutputStream outStream;

    private void sendReq(Object[] _req) {

        try {
            // write on the output stream
            outStream.writeObject(_req);
        } catch (IOException e) {
            System.out.println("Server disconnected!");
//                        e.printStackTrace();
        }
    }

}
